import { NextRequest, NextResponse } from 'next/server';
import { createSupabaseAdmin } from '@/lib/supabase';
import { createHash } from 'crypto';
import { 
  rateLimit, 
  sanitizeFilename, 
  validateFileSize, 
  validateLoanId,
  sanitizeError,
  addSecurityHeaders,
  logSecurityEvent 
} from '@/lib/security';

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

export async function POST(request: NextRequest) {
  try {
    // Rate limiting
    const rateLimitResponse = rateLimit(request);
    if (rateLimitResponse) return addSecurityHeaders(rateLimitResponse);

    const formData = await request.formData();
    const file = formData.get('file') as File;
    const loanId = formData.get('loanId') as string;

    // Input validation
    if (!file) {
      return addSecurityHeaders(NextResponse.json(
        { error: 'No file provided' },
        { status: 400 }
      ));
    }

    if (!loanId || !validateLoanId(loanId)) {
      logSecurityEvent('Invalid loan ID', { loanId });
      return addSecurityHeaders(NextResponse.json(
        { error: 'Invalid loanId format' },
        { status: 400 }
      ));
    }

    // Validate file size
    if (!validateFileSize(file.size, MAX_FILE_SIZE)) {
      logSecurityEvent('File size exceeded', { size: file.size, loanId });
      return addSecurityHeaders(NextResponse.json(
        { error: `File size must be less than ${MAX_FILE_SIZE / 1024 / 1024}MB` },
        { status: 400 }
      ));
    }

    // Validate file type
    const allowedTypes = [
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
    ];
    
    if (!allowedTypes.includes(file.type)) {
      logSecurityEvent('Invalid file type', { type: file.type, loanId });
      return addSecurityHeaders(NextResponse.json(
        { error: 'Invalid file type. Only PDF and Excel files are allowed.' },
        { status: 400 }
      ));
    }

    // Create unique file path with sanitized filename
    const timestamp = Date.now();
    const sanitizedFileName = sanitizeFilename(file.name);
    const filePath = `${loanId}/${timestamp}_${sanitizedFileName}`;

    // Get file buffer
    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);

    // Calculate file hash for duplicate detection
    const fileHash = createHash('sha256').update(buffer).digest('hex');

    // Initialize Supabase once
    const supabase = createSupabaseAdmin();

    // Check for duplicate file (same hash)
    const { data: existingUpload } = await supabase
      .from('uploads')
      .select('id, file_name, uploaded_at')
      .eq('file_hash', fileHash)
      .eq('loan_id', loanId)
      .single();

    if (existingUpload) {
      console.log(`⚠️ Duplicate file detected - hash: ${fileHash}`);
      return addSecurityHeaders(NextResponse.json({
        error: 'This file has already been uploaded',
        duplicate: true,
        existingUpload: {
          id: existingUpload.id,
          fileName: existingUpload.file_name,
          uploadedAt: existingUpload.uploaded_at,
        }
      }, { status: 409 })); // 409 Conflict
    }

    // Upload to Supabase Storage
    
    const { error: uploadError } = await supabase
      .storage
      .from('financials')
      .upload(filePath, buffer, {
        contentType: file.type,
        upsert: false,
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      return NextResponse.json(
        { error: `Upload failed: ${uploadError.message}` },
        { status: 500 }
      );
    }

    // Get public URL
    const { data: urlData } = supabase
      .storage
      .from('financials')
      .getPublicUrl(filePath);

    // Save upload metadata to database - let Postgres generate UUID
    const { data: uploadRecord, error: docError } = await supabase
      .from('uploads')
      .insert({
        loan_id: loanId,
        file_url: urlData?.publicUrl,
        file_path: filePath,
        file_name: file.name,
        file_size: file.size,
        file_hash: fileHash,
        mime_type: file.type,
        uploaded_at: new Date().toISOString(),
        parsing_status: 'uploaded',
        parsing_attempts: 0,
      })
      .select()
      .single();

    if (docError) {
      console.error('Database insert error:', docError);
      return addSecurityHeaders(NextResponse.json(
        { error: `Database error: ${docError.message}` },
        { status: 500 }
      ));
    }

    if (!uploadRecord) {
      return addSecurityHeaders(NextResponse.json(
        { error: 'Failed to create upload record' },
        { status: 500 }
      ));
    }

    // Get the UUID generated by Postgres
    const documentId = uploadRecord.id;

    return addSecurityHeaders(NextResponse.json({
      success: true,
      document: {
        id: documentId,
        loanId,
        fileName: sanitizeFilename(file.name),
        filePath,
        fileUrl: urlData?.publicUrl,
        fileSize: file.size,
        mimeType: file.type,
        status: 'uploaded',
        parsingStatus: 'uploaded',
      },
    }));
  } catch (error: unknown) {
    logSecurityEvent('Upload error', { error: sanitizeError(error) });
    return addSecurityHeaders(NextResponse.json(
      { error: sanitizeError(error) },
      { status: 500 }
    ));
  }
}

export async function GET(request: NextRequest) {
  try {
    // Rate limiting
    const rateLimitResponse = rateLimit(request);
    if (rateLimitResponse) return addSecurityHeaders(rateLimitResponse);

    const { searchParams } = new URL(request.url);
    const loanId = searchParams.get('loanId');

    // Validate loanId if provided
    if (loanId && !validateLoanId(loanId)) {
      logSecurityEvent('Invalid loan ID in GET', { loanId });
      return addSecurityHeaders(NextResponse.json(
        { error: 'Invalid loanId format' },
        { status: 400 }
      ));
    }

    const supabase = createSupabaseAdmin();

    let query = supabase.from('uploads').select('*').limit(100); // Prevent large queries
    
    if (loanId) {
      query = query.eq('loan_id', loanId);
    }

    const { data, error } = await query.order('uploaded_at', { ascending: false });

    if (error) {
      logSecurityEvent('Database error in upload GET', { error: error.message });
      return addSecurityHeaders(NextResponse.json(
        { error: sanitizeError(error) },
        { status: 500 }
      ));
    }

    return addSecurityHeaders(NextResponse.json({
      success: true,
      documents: data || [],
    }));
  } catch (error: unknown) {
    logSecurityEvent('Upload GET error', { error: sanitizeError(error) });
    return addSecurityHeaders(NextResponse.json(
      { error: sanitizeError(error) },
      { status: 500 }
    ));
  }
}
